/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-19 05:22:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import shop.dao.ProductRepository;
import java.util.List;
import shop.dto.Product;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("shop.dto.Product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("shop.dao.ProductRepository");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Products</title>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/meta.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/link.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
 
	String root = request.getContextPath(); 
	// 데이터 베이스에서 상품 목록 가져와서 그리드로 뿌려야될듯  required

      out.write("\r\n");
      out.write("<body>   \r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"px-4 py-5 my-5 text-center\">\r\n");
      out.write("		<h1 class=\"display-5 fw-bold text-body-emphasis\">상품 등록</h1>\r\n");
      out.write("		<div class=\"col-lg-6 mx-auto\">\r\n");
      out.write("			<p class=\"lead mb-4\">Shop 쇼핑몰 입니다.</p>\r\n");
      out.write("			<div class=\"d-grid gap-2 d-sm-flex justify-content-sm-center\">\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"container shop\" >\r\n");
      out.write("					<form action=\"");
      out.print(root );
      out.write("/shop/add_pro.jsp\" name=\"addForm\" method=\"get\" enctype=\"multipart/form-data\">\r\n");
      out.write("					\r\n");
      out.write("						<div class=\"input-group mb-3 row\">\r\n");
      out.write("							<label class=\"input-group-text col-md-2\" id=\"\">상품 이미지</label>\r\n");
      out.write("							<input type=\"file\" class=\"form-control col-md-10\" name=\"file\" placeholder=\"선택된 파일 없음\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"input-group mb-3 row\">\r\n");
      out.write("							<label class=\"input-group-text col-md-2\" id=\"\">상품코드</label>\r\n");
      out.write("							<input type=\"text\" class=\"form-control col-md-8\" name=\"productId\">\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"input-group mb-3 row\">\r\n");
      out.write("							<label class=\"input-group-text col-md-2\" id=\"\">상품명</label>\r\n");
      out.write("							<input type=\"text\" class=\"form-control col-md-8\" name=\"name\">\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"input-group mb-3 row\">\r\n");
      out.write("							<label class=\"input-group-text col-md-2\" id=\"\">가격</label>\r\n");
      out.write("							<input type=\"number\" class=\"form-control col-md-8\" name=\"unitPrice\">\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"input-group mb-3 row\">\r\n");
      out.write("							<div class=\"col-md-12 p-0\">\r\n");
      out.write("								<label class=\"input-group-text\" id=\"\">상세 정보</label>\r\n");
      out.write("							</div>\r\n");
      out.write("								<div class=\"col-md-12\">\r\n");
      out.write("									<textarea class=\"form-control\" style=\"heigth: 200px !improtant;\" name=\"description\"></textarea>\r\n");
      out.write("								</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"input-group mb-3 row\">\r\n");
      out.write("							<label class=\"input-group-text col-md-2\" id=\"\">제조사</label>\r\n");
      out.write("							<input type=\"text\" class=\"form-control col-md-8\" name=\"manufacturer\">\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"input-group mb-3 row\">\r\n");
      out.write("							<label class=\"input-group-text col-md-2\" id=\"\">분류</label>\r\n");
      out.write("							<input type=\"text\" class=\"form-control col-md-8\" name=\"category\">\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"input-group mb-3 row\">\r\n");
      out.write("							<label class=\"input-group-text col-md-2\" id=\"\">재고 수</label>\r\n");
      out.write("							<input type=\"number\" class=\"form-control col-md-8\"  name=\"unitsInStock\">\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"input-group mb-3 row\">\r\n");
      out.write("							<label class=\"input-group-text col-md-2\" id=\"\">상태</label>\r\n");
      out.write("							<div class=\"col-md-8 d-flex align-items-center\">\r\n");
      out.write("								<div class=\"radio-box d-flex\">\r\n");
      out.write("									<div class=\"radio-item mx-3\">\r\n");
      out.write("										<input type=\"radio\" class=\"form-check-input\" name=\"condition\" value=\"신규 제품\" value=\"NEW\" id=\"condition-new\"> \r\n");
      out.write("										<label for=\"condition-new\">신규 제품</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"radio-item mx-3\">\r\n");
      out.write("										<input type=\"radio\" class=\"form-check-input \" name=\"condition\" value=\"중고 제품\" value=\"OLD\" id=\"condition-old\"> \r\n");
      out.write("										<label for=\"condition-old\">중고 제품</label>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("									<div class=\"radio-item mx-3\">\r\n");
      out.write("										<input type=\"radio\" class=\"form-check-input \" name=\"condition\" value=\"재생 제품\" value=\"RE\" id=\"condition-re\"> \r\n");
      out.write("										<label for=\"condition-re\">재생 제품</label>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>						\r\n");
      out.write("						<div class=\"container p-5\">\r\n");
      out.write("						    <div class=\"row justify-content-between\">\r\n");
      out.write("						        <div class=\"col-auto\">\r\n");
      out.write("						            <a href=\"");
      out.print( root );
      out.write("/shop/products.jsp\" class=\"btn btn-secondary btn-lg\">목록</a>\r\n");
      out.write("						        </div>\r\n");
      out.write("						        <div class=\"col-auto\">\r\n");
      out.write("						            <input type=\"submit\" value=\"등록\">\r\n");
      out.write("						        </div>\r\n");
      out.write("						    </div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div><!-- 메인컨테이너 끝 -->\r\n");
      out.write("				\r\n");
      out.write("						\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/script.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
