/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-24 06:59:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import shop.dto.Product;
import java.util.List;
import shop.dao.ProductRepository;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1713335749197L));
    _jspx_dependants.put("jar:file:/C:/JSLEE/project/Market/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shop_Test/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("shop.dto.Product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("shop.dao.ProductRepository");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Shop</title>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/meta.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/link.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 
	String root = request.getContextPath(); 
	String productId = request.getParameter("productId");
	
	ProductRepository productDAO = new ProductRepository();
    List<Product> cartList = (List<Product>) session.getAttribute("cartList");
   
    if (productId != null) {
        Product product = productDAO.getProductById(productId);
        if (product != null) {
            if (cartList == null) {
                cartList = new ArrayList<Product>();
                session.setAttribute("cartList", cartList);
            }
            boolean duplicate = false;
            for (Product item : cartList) {
                if (item.getProductId().equals(productId)) {
                    duplicate = true;
                    item.setQuantity(item.getQuantity() + 1);
                    break;
                }
            }
            
            if (!duplicate) {
                product.setQuantity(1);
                cartList.add(product);
            }

            response.sendRedirect("products.jsp");
	    } else
	        response.sendRedirect("error.jsp");
	}
    
    // 로그인 확인
    String loginId = (String) session.getAttribute("loginId");
	boolean checkLogin = false;
	String loginform = "";
	
	if(loginId != null) checkLogin = true;	
	
	if(checkLogin) loginform = "회원 주문";
	else loginform = "비회원 주문";
	
	String name = request.getParameter("name");
	String deliveryDate = request.getParameter("deliveryDate");
	String nation = request.getParameter("nation");
	String zipCode = request.getParameter("zipCode");
	String address = request.getParameter("address");
 	String phone = request.getParameter("phone");
 	int sum = 0;

      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"px-4 py-5 mt-5 text-center\">\r\n");
      out.write("		<h1 class=\"display-5 fw-bold text-body-emphasis\">주문 정보</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container shop p-5 mb-5\" >\r\n");
      out.write("		<form action=\"complete.jsp\" method=\"post\">\r\n");
      out.write("			<!-- 주문 정보 -->\r\n");
      out.write("			<div class=\"ship-box\">\r\n");
      out.write("				<table class=\"table\">\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>주문형태 : </td>\r\n");
      out.write("							<td>");
      out.print( loginform );
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>성명 : </td>\r\n");
      out.write("							<td>");
      out.print(name );
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>우편번호 : </td>\r\n");
      out.write("							<td>");
      out.print(zipCode );
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>주소 : </td>\r\n");
      out.write("							<td>");
      out.print(address );
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>배송일 : </td>\r\n");
      out.write("							<td>");
      out.print(deliveryDate );
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>전화번호 : </td>\r\n");
      out.write("							<td>");
      out.print(phone );
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>주문 비밀번호 : </td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" name=\"orderPw\">\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>			\r\n");
      out.write("			<!-- 표 -->\r\n");
      out.write("			<div class=\"container mt-5\">\r\n");
      out.write("				    <table class=\"table table-striped table-hover table-bordered text-center align-middle\">\r\n");
      out.write("				        <thead class=\"table-primary\">\r\n");
      out.write("				            <tr>\r\n");
      out.write("				                <th>상품</th>\r\n");
      out.write("				                <th>가격</th>\r\n");
      out.write("				                <th>수량</th>\r\n");
      out.write("				                <th>소계</th>\r\n");
      out.write("				                <th>비고</th>\r\n");
      out.write("				            </tr>\r\n");
      out.write("				        </thead>\r\n");
      out.write("				        <tbody>\r\n");
      out.write("				            ");
 if (cartList != null && !cartList.isEmpty()) {
				                for (Product product : cartList) {
				                	int unitPrice = product.getUnitPrice() == null ? 0 : product.getUnitPrice();
				                	
				                    int total = unitPrice * product.getQuantity();
				                    sum += total;
				            
      out.write("\r\n");
      out.write("				            <tr>\r\n");
      out.write("				                <td>");
      out.print( product.getName() );
      out.write("</td>\r\n");
      out.write("				                <td>");
      out.print( product.getUnitPrice() );
      out.write("</td>\r\n");
      out.write("				                <td>");
      out.print( product.getQuantity() );
      out.write("</td>\r\n");
      out.write("				                <td>");
      out.print( total );
      out.write("</td>\r\n");
      out.write("				                <td>\r\n");
      out.write("				                </td>\r\n");
      out.write("				            </tr>\r\n");
      out.write("				            ");
 } 
      out.write("\r\n");
      out.write("				            <tr>\r\n");
      out.write("				                <td colspan=\"3\">총액</td>\r\n");
      out.write("				                <td>");
      out.print( sum );
      out.write("</td>\r\n");
      out.write("				                <td></td>\r\n");
      out.write("				            </tr>\r\n");
      out.write("				            ");
 } else { 
      out.write("\r\n");
      out.write("				            <tr>\r\n");
      out.write("				                <td colspan=\"5\">장바구니에 담긴 상품이 없습니다.</td>\r\n");
      out.write("				            </tr>\r\n");
      out.write("				            ");
 } 
      out.write("\r\n");
      out.write("				        </tbody>\r\n");
      out.write("				    </table>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 배송 정보 전달 -->\r\n");
      out.write("				<input type=\"hidden\" name=\"orderForm\" value=\"");
      out.print( loginform );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"name\" value=\"");
      out.print( name );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"deliveryDate\" value=\"");
      out.print( deliveryDate );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"nation\" value=\"");
      out.print( nation );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"zipCode\" value=\"");
      out.print( zipCode );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"address\" value=\"");
      out.print( address );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"phone\" value=\"");
      out.print( phone );
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"sum\" value=\"");
      out.print( sum );
      out.write("\">\r\n");
      out.write("				<div class=\"d-md-flex justify-content-between mt-5 mb-5\">\r\n");
      out.write("					<div>\r\n");
      out.write("					 	<a href=\"ship.jsp\" class=\"btn btn-lg btn-success\">이전</a>\r\n");
      out.write("						<a href=\"../index.jsp\" class=\"btn btn-lg btn-danger\">취소</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"submit\" class=\"btn btn-lg btn-primary\" value=\"주문완료\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/script.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
