/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-29 05:43:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import shop.dao.ProductRepository;
import java.util.List;
import shop.dto.Product;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1713335749197L));
    _jspx_dependants.put("jar:file:/C:/JSLEE/project/Market/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Shop_Test/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("shop.dto.Product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("shop.dao.ProductRepository");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Shop</title>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/meta.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/link.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
 
	String root = request.getContextPath(); 
	String productId = request.getParameter("productId");
	
	ProductRepository productDao = new ProductRepository();
	Product product = productDao.getProductById(productId);

      out.write("\r\n");
      out.write("<body>   \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"px-4 py-5 my-5 text-center\">\r\n");
      out.write("		<h1 class=\"display-5 fw-bold text-body-emphasis\">상품 수정</h1>\r\n");
      out.write("		<div class=\"col-lg-6 mx-auto\">\r\n");
      out.write("			<p class=\"lead mb-2\">Shop 쇼핑몰 입니다.</p> <br><br>\r\n");
      out.write("			<div class=\"d-grid gap-2 d-sm-flex justify-content-sm-center\">\r\n");
      out.write("	            <img class=\"card-img-top\" src=\"");
      out.print( root );
      out.print( product.getFile() );
      out.write("\" alt=\"");
      out.print( product.getName() );
      out.write("\" style=\"width:100%; max-width: 400px;\">\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <br><br><br>\r\n");
      out.write("			<div class=\"d-grid gap-2 d-sm-flex justify-content-sm-center\">\r\n");
      out.write("				<form action=\"update_pro.jsp\" name=\"product\" method=\"post\" onsubmit=\"return checkProduct()\" enctype=\"multipart/form-data\">\r\n");
      out.write("					<div class=\"input-group mb-3 row\">\r\n");
      out.write("						<label class=\"input-group-text col-md-4\" id=\"file\">상품 이미지</label>\r\n");
      out.write("						<input type=\"file\" class=\"form-control col-md-8\" name=\"file\" placeholder=\"상품이미지\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group mb-3 row\">\r\n");
      out.write("						<label class=\"input-group-text col-md-4\" id=\"productId\">상품 코드</label>\r\n");
      out.write("						<input type=\"text\" class=\"form-control col-md-8\" name=\"productId\" value=\"");
      out.print( product.getProductId() );
      out.write("\" required >\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group mb-3 row\">\r\n");
      out.write("						<label class=\"input-group-text col-md-4\" id=\"name\">상품명</label>\r\n");
      out.write("						<input type=\"text\" class=\"form-control col-md-8\" name=\"name\" value=\"");
      out.print( product.getName() );
      out.write("\" required >\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group mb-3 row\">\r\n");
      out.write("						<label class=\"input-group-text col-md-4\" id=\"unitPrice\">가격</label>\r\n");
      out.write("						<input type=\"text\" class=\"form-control col-md-8\" name=\"unitPrice\" value=\"");
      out.print( product.getUnitPrice() );
      out.write("\" required >\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group mb-3 row\">\r\n");
      out.write("						<label class=\"input-group-text row-md-4 rounded-end\" id=\"description\">상세 정보</label>\r\n");
      out.write("						<input type=\"text\" class=\"form-control form-control-lg col-md-12 rounded-start\" style=\"height: 100px;\" name=\"description\" value=\"");
      out.print( product.getDescription() );
      out.write("\" required >\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group mb-3 row\">\r\n");
      out.write("						<label class=\"input-group-text col-md-4\" id=\"manufacturer\">제조사</label>\r\n");
      out.write("						<input type=\"text\" class=\"form-control col-md-8\" name=\"manufacturer\" value=\"");
      out.print( product.getManufacturer() );
      out.write("\" required >\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group mb-3 row\">\r\n");
      out.write("						<label class=\"input-group-text col-md-4\" id=\"category\">분류</label>\r\n");
      out.write("						<input type=\"text\" class=\"form-control col-md-8\" name=\"category\" value=\"");
      out.print( product.getCategory() );
      out.write("\"required >\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"input-group mb-3 row\">\r\n");
      out.write("						<label class=\"input-group-text col-md-4\" id=\"unitsInStock\">재고 수</label>\r\n");
      out.write("						<input type=\"text\" class=\"form-control col-md-8\" name=\"unitsInStock\" value=\"");
      out.print( product.getUnitsInStock() );
      out.write("\" required >\r\n");
      out.write("					</div>\r\n");
      out.write("				   <div class=\"input-group mb-3 row\">\r\n");
      out.write("					<div class=\"col-md-4 p-0\">\r\n");
      out.write("						<label class=\"input-group-text\" id=\"\">상태</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-8 d-flex align-items-center\">\r\n");
      out.write("						<div class=\"radio-box d-flex small\">\r\n");
      out.write("							<div class=\"radio-item mx-3\">\r\n");
      out.write("						    <input type=\"radio\" class=\"form-check-input\" name=\"condition\" value=\"NEW\" id=\"condition-new\" required\r\n");
      out.write("	                        ");
      out.print( (product.getCondition() != null && product.getCondition().equals("NEW")) ? "checked" : "" );
      out.write(" >  \r\n");
      out.write("						    <label for=\"newProduct\" class=\"small\">신규 제품</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"radio-item mx-3\" >\r\n");
      out.write("						    <input type=\"radio\" class=\"form-check-input\" name=\"condition\" value=\"OLD\" id=\"condition-old\"\r\n");
      out.write("   	                        ");
      out.print( (product.getCondition() != null && product.getCondition().equals("OLD")) ? "checked" : "" );
      out.write(" >  \r\n");
      out.write("						    <label for=\"usedProduct\" class=\"small\">중고 제품</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"radio-item mx-3\">\r\n");
      out.write("						    <input type=\"radio\" class=\"form-check-input\" name=\"condition\" value=\"RE\" id=\"condition-re\"\r\n");
      out.write("   	                        ");
      out.print( (product.getCondition() != null && product.getCondition().equals("RE")) ? "checked" : "" );
      out.write(" >  \r\n");
      out.write("						    <label for=\"recycledProduct\" class=\"small\">재생 제품</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				 	</div>\r\n");
      out.write("				 		<div class=\"container\">\r\n");
      out.write("					    <div class=\"row justify-content-between\">\r\n");
      out.write("					        <div class=\"col-auto\">\r\n");
      out.write("					            <a href=\"");
      out.print( root );
      out.write("/shop/products.jsp\" class=\"btn btn-secondary btn-lg\">목록</a>\r\n");
      out.write("					        </div>\r\n");
      out.write("					        <div class=\"col-auto\">\r\n");
      out.write("					            <button type=\"submit\" class=\"btn btn-success btn-lg\">수정</button>\r\n");
      out.write("					        </div>\r\n");
      out.write("					    </div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/layout/script.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
